export const constants = {
	CREATE_A_JOB: 'Create a job',
	EDIT_THE_JOB: 'Edit the job',
	STEP: 'Step',
	JOB_TITLE: 'Job title',
	COMPANY_NAME: 'Company name',
	INDUSTRY: 'Industry',
	LOCATION: 'Location',
	REMOTE_TYPE: 'Remote type',
	NEXT: 'Next',
	EXPERIENCE: 'Experience',
	SALARY: 'Salary',
	TOTAL_EMPLOYEE: 'Total employee',
	EMPLOYEES: 'Employees',
	SAVE: 'Save',
	APPLY_TYPE: 'Apply Type',
	MAXIMUM: 'Maximum',
	MINIMUM: 'Minimum',
	EX_100: 'ex. 100',
	QUICK_APPLY: 'Apply now',
	EXTERNAL_APPLY: 'External apply',
	GREAT_VIBES: 'Great Vibes',
	INFORMATION_TECHNOLOGY: 'ex. Information Technology',
	CHENNAI: 'ex. Chennai',
	INDIA: 'India',
	TAMILNADU: 'Tamilnadu',
	IN_OFFICE: 'ex. In-office',
	PART_TIME: 'Part-Time',
	INR: 'INR',
	YEARS: 'Years',
	MONTH: 'Month',
	AM: 'am',
	GOOGLE: 'ex. Google',
	PM: 'pm',
	IST: 'IST',
	APPLY_NOW: 'Apply Now',
	UX_UI_DESIGNER: 'ex. UX UI Designer',
	DEVELOPER: 'Developer',
	INTERACTION_DESIGNER: 'Interaction Designer',
	SEO_ANALYST: 'SEO Analyst',
	JOB: 'Job',
	BASE_URL: 'https://64f46d5a932537f4051a5948.mockapi.io/gohire/jobs/',
	EDIT: 'edit',
	DELETE: 'delete',
	NO_JOBS: 'No jobs created. Please create one.',
	CANCEL: 'Cancel',
	NUMBER: 'number',
};
