export const constants = {
	CREATE_A_JOB: 'Create a job',
	EDIT_THE_JOB: 'Edit the job',
	STEP: 'Step',
	JOB_TITLE: 'Job title',
	COMPANY_NAME: 'Company name',
	INDUSTRY: 'Industry',
	LOCATION: 'Location',
	REMOTE_TYPE: 'Remote type',
	NEXT: 'Next',
	EXPERIENCE: 'Experience',
	SALARY: 'Salary',
	TOTAL_EMPLOYEE: 'Total employee',
	EMPLOYEES: 'Employees',
	SAVE: 'Save',
	APPLY_TYPE: 'Apply Type',
	MAXIMUM: 'Maximum',
	MINIMUM: 'Minimum',
	EX_100: 'ex. 100',
	QUICK_APPLY: 'Apply now',
	EXTERNAL_APPLY: 'External apply',
	GREAT_VIBES: 'Great Vibes',
	INFORMATION_TECHNOLOGY: 'ex. Information Technology',
	CHENNAI: 'ex. Chennai',
	INDIA: 'India',
	TAMILNADU: 'Tamilnadu',
	IN_OFFICE: 'ex. In-office',
	PART_TIME: 'Part-Time',
	INR: 'INR',
	YEARS: 'Years',
	MONTH: 'Month',
	AM: 'am',
	GOOGLE: 'ex. Google',
	PM: 'pm',
	IST: 'IST',
	APPLY_NOW: 'Apply Now',
	UX_UI_DESIGNER: 'ex. UX UI Designer',
	DEVELOPER: 'Developer',
	INTERACTION_DESIGNER: 'Interaction Designer',
	SEO_ANALYST: 'SEO Analyst',
	JOB: 'Job',
	BASE_URL: 'https://64f46d5a932537f4051a5948.mockapi.io/gohire/jobs/',
	EDIT: 'edit',
	DELETE: 'delete',
	NO_JOBS: 'No jobs created. Please create one.',
	CANCEL: 'Cancel',
	NUMBER: 'number',
	LOGO_URL:
		'https://lh3.googleusercontent.com/pw/AIL4fc9WTLwRlZXmfV2iY6GWexSxL19-b7Pz4pTbV_qlo4yV16_iPy6Vm37-OTB2NhevNeyEHfgUBLb0GLboRtElEIlW9d1QpP5Ub_eKTKy_Z36szUuDw_TYCPN5UWpRa6ZwLtyC3c7w3nF9R9gBKlEWjHy-jDlxgE81tq31CP328nBLyrBSuy8LvMgCcEnE8epDmWx_hUlbK3Hx-2e5ieDVfx0YmNLj5mqjGIWiChiz-78Xb_Lsqdf6MdeJW5eP-6xWWkza8LyJcQ-dpjMFDsoGXCEtbNhTo4Y_IdPGHG_sU9fOZZt9zuvY78epEOOjLGI158h93MjHZu2o6nahpVypDoY4MFlfJlEBPFZiGBG3f3jzhBDvNLjW1p-TDcIEUhaxIv7-dh6W0gunZ9kOqltRo_SzDMO3evP5lUjiyGmqNiA_eJk06KjAQim9EGsxx5skQzy5G2ps_BRXMUhyZyDPdY9CyO9RbFQMRqIkMOOI5E_JiTF1U_dOiW8IjyF7W41YBJUwbPGwo0PcSSCgIm3N8BMwHdN8rd0heIRFBW84PXuQCtgDntPCm918nNLQNsQ5mYdvcuuqtLOVbsFJ-9RzZpVqdrsuFTY4tjOAfNyzFg3Ennz8OIoXUtyi-70qTG0ISgM6UMnYZOBZjj_9sZmTq1Z-YiOEv7TnxLTAfzx-AT2IBMjuB3vPOMcLSO_9Uu__MRp9K-iIsu-xASFK-lgZ7tJJtwpa-xaFut6rYvXoJv_QT4XKV6h0UR_vv1ceAUrBYudw7bqzRSC52KKHVrbI3xRNlLMEQcefr5Lvbl-h86yJOaLbU7TIiryORZU0d_Ht6L7yuRmmEVl9T7FSssevViegId0PQ6lNLAzx22iXzaIu_HmhKKu_w_TLa6jpiiM3ldu1E4JT9MtQtWZsM0f_beZ6N-HUn-u_n_k6MWFMzwZKNHq1dY8aV_yQ-20kit2D7IQr0opIBQRimMgFv2w_gZqzUaNcRFfPcd296OdRN4nCq-KoDbG-QakKH12nzcw2EJ0=w48-h48-s-no?authuser=0',
};
